# Generated by Django 4.2.4 on 2023-10-29 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='applicant_form',
            new_name='picture',
        ),
    ]
