# Generated by Django 4.2.4 on 2023-10-29 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0002_rename_applicant_form_message_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='picture',
            new_name='profile_picture',
        ),
    ]
